Repository swe574-spring23/SWE574, pull requests merged in 2023-04, with the labels that each got.

#85 DEV | Add bookmark button
  SWE574_project/settings.py
  posts/templates/add_comment_to_post.html
  posts/templates/post_detail.html
  posts/templates/post_list.html
  posts/tests/tests.py
  posts/urls.py
  posts/views.py
  spaces/templates/post_detail.html
  spaces/templates/post_edit.html
  users/migrations/0008_user_bookmarks.py
  users/models.py
  users/templates/my_account.html
  users/tests/factories.py
  users/tests/tests.py
  users/views.py
Labels: Component: Back-end, Info: Has Migration

#89 DEV | Share Post in Spaces and Space Recommendations
  posts/forms.py
  posts/views.py
  spaces/models.py
  spaces/templates/my_spaces_list.html
  spaces/templates/post_edit.html
  spaces/templates/space_detail.html
  spaces/tests/tests.py
  spaces/views.py
Labels: Type: Enhancement, Component: Back-end, Component: Front-end, Priority: Medium

#101 DEV | Remove Members | Grant Permission | Ungrant Permission | Remove Moderators
  posts/templates/post_detail.html
  posts/views.py
  spaces/templates/space_members.html
  spaces/tests/tests.py
  spaces/urls.py
  spaces/views.py
Labels: Type: Enhancement, Component: Back-end, Component: Front-end, Priority: Medium

#104 DEV | Space Detail Page Design Updates
  spaces/forms.py
  spaces/templates/space_detail.html
  spaces/templates/space_policies.html
Labels: Component: Front-end

#109 DEV | Bugfix for post list, follow and tags
  posts/templates/post_detail.html
  posts/templates/post_list.html
  posts/views.py
  users/admin.py
  users/migrations/0009_auto_20230420_1509.py
  users/models.py
  users/templates/user_detail.html
  users/urls.py
  users/views.py
Labels: Type: Bug, Info: Has Migration

#114 DEV | User Badges
  posts/static/images/badges/duck.jfif
  posts/static/images/badges/duck_IGx60O7.jfif
  posts/static/images/badges/duck_muhGmLw.jfif
  posts/templates/base.html
  posts/tests/tests.py
  spaces/tests/tests.py
  users/admin.py
  users/apps.py
  users/migrations/0010_badge_userbadge.py
  users/migrations/0011_auto_20230424_1558.py
  users/migrations/0012_badge_userbadge.py
  users/models.py
  users/signals.py
  users/templates/user_detail.html
  users/views.py
Labels: Priority: Medium

#115 DEV | Automatic Badge Creation at Initial Step
  spaces/templates/space_detail.html
  spaces/tests/tests.py
  spaces/urls.py
  spaces/views.py
  users/apps.py
  users/signals.py
Labels: Component: Back-end
