Repository swe574-spring23/SWE574, pull requests merged in 2023-03, with the labels that each got.

#7 DEV | Add docs for wiki pages
  .github/pull_request_template.md
  .gitignore
  README.md
  docs/backend-handbook/coding-style-guide.md
  docs/github/developing-new-feature
  docs/weekly-notes/week1.md
Labels: Type: Documentation

#9 DEV | Add boun logo
  README.md
  docs/boun.png
Labels: Type: Bug, Type: Documentation

#15 DEV | Home Page Updates
  img.png
  uploads/file.pdf
  uploads/file_10agqu7.pdf
  uploads/file_3a9hN1z.pdf
  uploads/file_A1kF9YP.pdf
  uploads/file_JoWYoRe.pdf
  uploads/file_nzD4n07.pdf
  uploads/file_xJO3zLN.pdf
Labels: Type: Enhancement

#16 week 1 - adding table
  docs/weekly-notes/week1.md
Labels: Type: Documentation

#22 DEV | Check Existing Link function added and Code Refactorings have been made.
  .idea/workspace.xml
  posts/templates/posts/base.html
  posts/templates/posts/post_edit.html
  posts/templates/posts/post_list.html
  posts/urls.py
  posts/views.py
Labels: Type: Enhancement, Component: Back-end, Component: Front-end, Priority: Medium

#23 Week2 Meeting
  docs/weekly-notes/week1.md
  docs/weekly-notes/week2.md
Labels: Type: Documentation

#24 DEV | Update project structure
  LICENSE.txt
  SWE574_project/__init__.py
  SWE574_project/asgi.py
  SWE574_project/settings.py
  SWE574_project/urls.py
  SWE574_project/wsgi.py
  authenticator/migrations/0001_initial.py
  authenticator/models.py
  core/__init__.py
  core/decorators.py
  docker-compose.yml
  docs/backend-handbook/how-to-use-github.md
  manage.py
  posts/admin.py
  posts/forms.py
  posts/migrations/0001_initial.py
  posts/migrations/0002_auto_20230311_1819.py
  posts/migrations/0002_post_image.py
  posts/migrations/0003_auto_20230305_1048.py
  posts/migrations/0004_auto_20230305_1058.py
  posts/migrations/0005_space.py
  posts/migrations/0006_post_spaces.py
  posts/migrations/0007_auto_20230305_2055.py
  posts/models.py
  posts/urls.py
  posts/views.py
  tools/exec_bash.sh
  tools/run_development.sh
  users/__init__.py
  users/admin.py
  users/apps.py
  users/forms.py
  users/migrations/0001_initial.py
  users/migrations/__init__.py
  users/models.py
  users/static/css/account.css
  users/static/css/account.style.css
  users/templates/base.html
  users/templates/edit.html
  users/templates/eralp.html
  users/templates/login.html
  users/templates/password_change_done.html
  users/templates/password_change_form.html
  users/templates/password_reset_complete.html
  users/templates/password_reset_confirm.html
  users/templates/password_reset_done.html
  users/templates/password_reset_email.html
  users/templates/password_reset_form.html
  users/templates/register.html
  users/tests.py
  users/urls.py
  users/views.py
Labels: Info: Caution, Type: Technical Debt, Info: Has Migration

#29 Annotation | Start-off the app
  SWE574_project/settings.py
Labels: Type: Enhancement, Priority: High, Component: Back-end, Component: Front-end

#36 `DEV | Base.html update
  posts/templates/posts/base.html
Labels: Priority: Low

#40 DEV | My Own Spaces and Space Policy Update
  posts/migrations/0005_auto_20230313_2300.py
  posts/templates/base.html
  spaces/forms.py
  spaces/migrations/0002_auto_20230313_2300.py
  spaces/models.py
  spaces/templates/create_space.html
  spaces/templates/my_spaces_list.html
  spaces/templates/space_detail.html
  spaces/templates/space_list.html
  spaces/templates/space_policies.html
  spaces/urls.py
  spaces/views.py
  users/migrations/0003_auto_20230313_2300.py
Labels: Type: Enhancement, Component: Back-end, Component: Front-end

#50 DEV | Create week3 notes
  docs/weekly-notes/week3
Labels: Type: Documentation

#52 DEV | Front End Updates
  posts/migrations/0006_auto_20230320_1815.py
  posts/templates/base.html
  spaces/migrations/0004_alter_space_id.py
  users/migrations/0004_auto_20230320_1815.py
Labels: Component: Front-end

#55 DEV | Post to different Spaces
  posts/forms.py
  posts/migrations/0007_auto_20230321_2059.py
  posts/tests.py
  posts/urls.py
  posts/views.py
  spaces/migrations/0005_auto_20230321_2059.py
  spaces/templates/post_edit.html
  spaces/templates/space_detail.html
  users/migrations/0005_auto_20230321_2059.py
Labels: Type: Enhancement, Component: Back-end, Component: Front-end

#56 DEV | Made sidebar responsive
  posts/templates/base.html
  spaces/templates/create_space.html
  spaces/templates/post_edit.html
Labels: Type: Bug, Type: Enhancement, Priority: Medium

#54 DEV | Update developer handbook
  .gitignore
  docs/developer-handbook/developing-new-feature.md
  docs/developer-handbook/how-to-use-docker.md
  docs/developer-handbook/how-to-use-github.md
Labels: Type: Documentation

#48 DEV | GitHub workflow
  .github/workflows/check-base-branch.yml
  .github/workflows/django-tester.yml
  .github/workflows/linter.yml
  .github/workflows/proof-html.yaml
  SWE574_project/settings.py
  docs/developer-handbook/developing-new-feature.md
  requirements-development.txt
  sample.env.txt
Labels: Component: Devops

#58 DEV | Add user tests
  posts/tests.py
  users/tests.py
Labels: Component: Back-end

#61 DEV | Fixed space button
  spaces/templates/create_space.html
Labels: Type: Bug, Priority: Medium

#63 DEV | Space App Unit Tests Added
  posts/views.py
  spaces/tests.py
Labels: Info: Testing

#71 DEV | creating space recommendation first page
  docs/weekly-notes/week2.md
  users/templates/spaces_initial.html
  users/urls.py
  users/views.py
Labels: Info: Question, Component: Front-end

#81 DEV | Fix space_initial.html
  docs/weekly-notes/week2.md
  spaces/templates/spaces_initial.html
Labels: Type: Bug

#65 DEV | Enhance tests
  .gitignore
  SWE574_project/settings.py
  docker-compose.yml
  docs/developer-handbook/developing-new-feature.md
  docs/developer-handbook/testing.md
  docs/weekly-notes/week2.md
  docs/weekly-notes/week3
  posts/tests.py
  posts/tests/__init__.py
  posts/tests/factories.py
  posts/tests/tests.py
  spaces/tests/__init__.py
  spaces/tests/factories.py
  spaces/tests/tests.py
  users/tests/__init__.py
  users/tests/factories.py
  users/tests/tests.py
Labels: Component: Back-end
