Repository swe574-spring23/SWE574, pull requests merged in 2023-05, with the labels that each got.

#119 dev - Maria unittests
  docs/Comment Badge/30c272bf-3c0e-4d11-9ae0-da175222a2ec.svg
  docs/Comment Badge/35ce0c0c-e6e6-4b98-a792-30bfead392eb.svg
  docs/Comment Badge/3b4ea1c0-c975-4c51-afe5-28305e57afab.png
  docs/Comment Badge/8643c4dc-d777-4974-8b3f-4823fd9b1cc6.svg
  docs/Comment Badge/d75ec705-22d6-47e9-ae85-6f99b5db7bf9.png
  docs/Comment Badge/fed48fe2-0d3f-48f5-86a0-45eb1e2999a7.png
  docs/Follower Badges/37fae91f-65dd-4acb-a56f-d2876ae01504.svg
  docs/Follower Badges/6f09acaa-9ae2-450a-b050-9197fce7360b.png
  docs/Follower Badges/705fe21d-eb0a-4a0c-99ed-feb59518890e.png
  docs/Follower Badges/a6721fae-8cab-4fd3-82f0-1b3b4d480b58.svg
  docs/Follower Badges/bdb089d6-834e-4cbc-8e0d-7dd175b0acd0.png
  docs/Follower Badges/ff13ac51-0742-4ffa-992d-95b2f4df0e07.svg
  docs/Post Badges/4bf71702-d330-4d6c-b79a-28fdbf6357bf.png
  docs/Post Badges/8053d1b3-d603-4e7d-a505-68480c5add97.svg
  docs/Post Badges/99dd8aca-622d-472d-8891-603c21ea7861.svg
  docs/Post Badges/c83dfbc2-d8a7-4a16-8ce7-5b5a931add5f.svg
  docs/Post Badges/ca99a56a-ef6e-402a-a5ae-4c6c4d3700a5.png
  docs/Post Badges/d714c6a2-28dc-4e40-a97b-88eeff2a27ae.png
  docs/Space Badges/4155b27c-b914-422d-ab8e-a43eabfe7953.svg
  docs/Space Badges/859b9bd1-2232-42cc-a42b-0d6f58951b46.png
  docs/Space Badges/8fd5e6a2-c642-4bac-9222-897f36093b77.svg
  docs/Space Badges/a2afd501-55ee-47d4-b45e-13e326e7bbb6.png
  docs/Space Badges/beebb210-fbe5-4249-9b50-6d0b156462c4.svg
  docs/Space Badges/c10e96bd-2de0-4474-b262-da31ff6549cc.png
  posts/tests/tests.py
  spaces/templates/post_edit.html
Labels: Info: Testing

#120 DEV | Annotation Posting
  .github/workflows/django-tester.yml
  annotation_server/annotation_root/settings.py
  annotation_server/requirements.txt
  app_server/SWE574_project/settings.py
  app_server/posts/templates/post_list.html
  app_server/requirements.txt
Labels: Component: Back-end

#131 DEV | Text Annotations
  app_server/posts/templates/post_detail.html
Labels: Component: Front-end

#136 DEV | Add search for tag description
  app_server/posts/views.py
Labels: Type: Bug

#147 DEV | Feature | Annotation - Şahin "
  app_server/posts/templates/post_detail.html
Labels: Priority: Low

#141 DEV - Recommendation System
  app_server/core/management/commands/generate_data.py
  app_server/posts/models.py
  app_server/spaces/models.py
  app_server/spaces/views.py
Labels: Type: Enhancement, Priority: High, Component: Back-end

#139 DEV - Modifying frontend base file
  app_server/posts/templates/base.html
  app_server/posts/tests/tests.py
  app_server/spaces/templates/my_spaces_list.html
  app_server/users/tests/tests.py
Labels: Component: Front-end

#156 DEV | Add friend recommendations
  app_server/users/templates/user_list.html
  app_server/users/views.py
Labels: Priority: High, Component: Back-end, Component: Front-end

#154 DEV | Add fixes
  annotation_server/annotations/HELPER.md
  annotation_server/annotations/models.py
  annotation_server/annotations/serializers.py
  app_server/posts/templates/base.html
  app_server/spaces/views.py
  app_server/users/templates/eralp.html
  app_server/users/templates/my_bookmarks.html
  app_server/users/urls.py
  app_server/users/views.py
Labels: Type: Bug

#164 DEV | Annotation HTML fix
  app_server/posts/templates/base.html
  app_server/posts/templates/post_detail.html
  app_server/posts/templates/post_list.html
Labels: Component: Front-end

#159 DEV I Fix followed user duplication
  app_server/users/views.py
Labels: Component: Back-end, Component: Front-end, Priority: Medium

#165 DEV | Bug Fix
  app_server/posts/templates/post_detail.html
  app_server/posts/templates/post_list.html
  app_server/spaces/templates/my_spaces_list.html
Labels: Type: Bug, Type: Documentation, Type: Enhancement, Component: Back-end, Component: Front-end, Type: Research, Component: Devops

#166 DEV | Fixed image bug
  app_server/posts/forms.py
  app_server/posts/templates/post_detail.html
  app_server/posts/templates/post_list.html
  app_server/posts/views.py
Labels: Component: Front-end, Priority: Medium

#168 DEV | My Account Page Updated
  app_server/users/admin.py
  app_server/users/forms.py
  app_server/users/templates/my_account.html
  app_server/users/views.py
Labels: Component: Back-end, Component: Front-end

#171 DEV | Add Mock Data Labels
  app_server/core/management/commands/generate_data.py
Labels: Type: Bug, Component: Back-end

#172 DEV | Add user search & fix mybookmarks
  app_server/posts/migrations/0010_alter_post_text.py
  app_server/posts/models.py
  app_server/posts/templates/post_detail.html
  app_server/posts/templates/search.html
  app_server/posts/views.py
  app_server/users/models.py
  app_server/users/templates/my_bookmarks.html
  app_server/users/views.py
Labels: Type: Bug

#174 PROD | Deployment changes
  annotation_server/annotations/views.py
  app_server/posts/templates/post_detail.html
  app_server/posts/templates/post_list.html
  app_server/users/templates/my_bookmarks.html
Labels: Component: Devops

#175 DEV | Labels Fix
  app_server/posts/models.py
  app_server/posts/templates/post_detail.html
  app_server/posts/templates/post_list.html
Labels: Component: Back-end, Component: Front-end

#177 DEV | Semantic Tag
  app_server/posts/templates/post_detail.html
  app_server/posts/templates/post_list.html
Labels: Component: Back-end, Component: Front-end, Component: Devops

#178 DEV | Added creator part to json
  app_server/posts/templates/post_detail.html
  app_server/posts/templates/post_editor.html
  app_server/posts/views.py
Labels: Priority: High

#179 PROD | Bug Fixes
  app_server/posts/models.py
  app_server/posts/templates/post_detail.html
  app_server/posts/templates/post_editor.html
  app_server/posts/templates/post_list.html
  app_server/posts/views.py
Labels: Info: Caution, Component: Back-end, Component: Front-end

#181 PROD | Add annotation search
  app_server/SWE574_project/settings.py
  app_server/posts/templates/search.html
  app_server/posts/views.py
  app_server/requirements.txt
Labels: Type: Enhancement, Priority: High

#183 PROD | Sehmuzc patch 3
  app_server/spaces/templates/space_detail.html
Labels: Info: Testing

#184 PROD | Tag Filtering Change
  app_server/posts/views.py
Labels: Info: Caution
